In [ ]:
#"Lab 5 (Data Loading): Creating NumPy arrays, reading CSV files, introducing pandas
#Series/DataFrames, and performing basic indexing, filtering, and summary operations,
#along with inspecting shape, columns, and data types."

# Lab 5 (Data Loading)
In this lab you will learn about
* Creating NumPy Arrays
* Reading CSV Files
* Pandas Series
* Pandas DataFrames
* Basic Indexing and Filtering
* Summary Operations
* Inspecting Shape, Columns, and Data Types

### ▶ **Creating NumPy Arrays**
NumPy is the core library for numerical computing in Python. Its main object is the n-dimensional array, which is much faster and more memory-efficient than a normal Python list when doing numerical operations.

**Why not just use lists?**

Python lists can hold mixed data types and are flexible, but that flexibility makes them slow for math operations. NumPy arrays store data of a single type in contiguous memory, so operations on them are vectorized and fast.

First, we need to import the library. The common convention is to import it as `np`.

In [ ]:
import numpy as np
# Creating a 1D array from a list
a = np.array([10, 20, 30, 40, 50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>

**Creating 2D arrays (matrices)**

You can pass a list of lists to `np.array()` to create a 2D array.

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]

**Other handy ways to create arrays**

 `np.zeros(shape)` – array filled with 0's

 `np.ones(shape)` – array filled with 1's

 `np.arange(start, stop, step)` – like Python's `range()` but returns an array

 `np.linspace(start, stop, num)` – `num` evenly spaced values between start and stop

 `np.random.rand(shape)` – array of random values between 0 and 1

In [ ]:
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 3))
range_arr = np.arange(0, 10, 2)
lin_arr = np.linspace(0, 1, 5)
print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Arange:", range_arr)
print("Linspace:", lin_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]

**Array attributes**Every NumPy array has some useful attributes that tell you about its structure:* `.shape` – dimensions of the array (rows, columns)* `.ndim` – number of dimensions* `.size` – total number of elements* `.dtype` – data type of the elements

In [ ]:
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Size:", b.size)
print("Dtype:", b.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Dtype: int64

**Reshaping arrays**`.reshape()` lets you change the shape of an array without changing its data, as long as the total number of elements stays the same.

In [ ]:
c = np.arange(1, 13)
print("Original:", c)
c_reshaped = c.reshape(3, 4)
print("Reshaped (3x4):\n", c_reshaped)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

## ▶ Reading CSV Files

CSV (Comma Separated Values) is one of the most common formats for storing tabular data. Python's **pandas** library makes it very easy to load a CSV file into a table-like structure called a **DataFrame**.

For this lab we'll use a real-world **Amazon India product dataset** (`amazon.csv`) — 1465 products scraped from Amazon, with pricing, ratings, categories, and customer review data. Real datasets like this are rarely clean, which makes it a great way to learn what data loading actually looks like in practice. The dataset is provided to you already.

**Loading the file in VS Code**

Since you're running this notebook locally in VS Code (with the Jupyter extension), there's no upload button needed you just need the CSV file to be accessible on your computer, and you need to point `pd.read_csv()` to its correct path.

1. Download **`amazon.csv`** provided with this notebook.
2. Place it somewhere convenient e.g., the same folder as this notebook (recommended)
3. Note the **full path** to the file on your system.
4. Run the cell below with the path updated.

 **Note:** The path used in the code cell (e.g., `pd.read_csv("/content/amazon.csv")`) is a placeholder from a Google Colab environment. Since you're working in VS Code, replace it with your own file path, for example:

In [ ]:
import pandas as pd
df = pd.read_csv("C:/Users/YourName/Downloads/amazon.csv")
df

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

**A quick peek at the data*** `

.head(n)` – first `n` rows

.tail(n)` – last `n` rows

By default 5 rows are shown

In [ ]:
print(df.head())

   product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399
1  Computers&Accessories|Accessories&Peripherals|...             ₹199
2  Computers&Accessories|Accessories&Peripherals|...             ₹199
3  Computers&Accessories|Accessories&Peripherals|...             ₹329
4  Computers&Accessories|Accessories&Peripherals|...             ₹154

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269
1         ₹349                 43%    4.0       43,994
2       ₹1,899                 90%    3.9        7,928
3         ₹699                 53%    4.2       94,363
4         ₹399                 61%    4.2       16,905

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...
1  Compatible with all Type C enabled devices, be...
2  【 Fast Charger& Data Sync】-With built-in safet...
3  The boAt Deuce USB 300 2 in 1 cable is compati...
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...
1  A Good Braided Cable for Your Type C Device,Go...
2  Good speed for earlier versions,Good Product,W...
3  Good product,Good one,Nice,Really nice product...
4  As good as original,Decent,Good one for second...

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...
1  I ordered this cable to connect my phone to An...
2  Not quite durable and sturdy,https://m.media-a...
3  Good product,long wire,Charges good,Nice,I bou...
4  Bought this instead of original apple, does th...

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...
1  https://m.media-amazon.com/images/W/WEBP_40237...
2  https://m.media-amazon.com/images/W/WEBP_40237...
3  https://m.media-amazon.com/images/I/41V5FtEWPk...
4  https://m.media-amazon.com/images/W/WEBP_40237...

                                        product_link
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1  https://www.amazon.in/Ambrane-Unbreakable-Char...
2  https://www.amazon.in/Sounce-iPhone-Charging-C...
3  https://www.amazon.in/Deuce-300-Resistant-Tang...
4  https://www.amazon.in/Portronics-Konnect-POR-1...

In [ ]:

print(df.tail(3))

      product_id                                       product_name  \
1462  B009P2LIL4  Bajaj Majesty RX10 2000 Watts Heat Convector R...
1463  B00J5DYCCA  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1464  B01486F4G6  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...

                                               category discounted_price  \
1462  Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...           ₹2,219
1463  Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...           ₹1,399
1464  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,863

     actual_price discount_percentage rating rating_count  \
1462       ₹3,080                 28%    3.6          468
1463       ₹1,890                 26%      4        8,031
1464       ₹3,690                 22%    4.3        6,987

                                          about_product  \
1462  International design and styling|Two heat sett...
1463  Fan sweep area: 230 MM ; Noise level: (40 - 45...
1464  Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...

                                                user_id  \
1462  AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...
1463  AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...
1464  AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...

                                              user_name  \
1462  Nehal Desai,Danish Parwez,Amazon Customer,Amaz...
1463  Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...
1464  Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...

                                              review_id  \
1462  R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...
1463  R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...
1464  R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...

                                           review_title  \
1462  very good,Work but front melt after 2 month,Go...
1463  Fan Speed is slow,Good quality,Good product,go...
1464  Works perfect,Ok good product,Nice Product. Re...

                                         review_content  \
1462  plastic but cool body ,u have to find sturdy s...
1463  I have installed this in my kitchen working fi...
1464  It does it job perfectly..only issue is temp c...

                                               img_link  \
1462  https://m.media-amazon.com/images/W/WEBP_40237...
1463  https://m.media-amazon.com/images/W/WEBP_40237...
1464  https://m.media-amazon.com/images/W/WEBP_40237...

                                           product_link
1462  https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463  https://www.amazon.in/Havells-Ventilair-230mm-...
1464  https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

### ▶ **Inspecting Shape, Columns, and Data Types**

Before doing anything else with a new dataset, it's good practice to inspect its structure:*

`.shape` – (rows, columns)*

`.columns` – list of column names*

`.dtypes` – data type of each column*

`.info()` – a concise summary of the DataFrame (dtypes, non-null counts, memory usage)

In [ ]:
print("Shape:", df.shape)
print()
print("Columns:", df.columns)
print()
print("Dtypes:\n", df.dtypes)

Shape: (1465, 16)

Columns: Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='object')

Dtypes:
 product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

**Notice something?** Columns like `discounted_price`, `actual_price`, `discount_percentage`, `rating`, and `rating_count` all show up as `object` (text) dtype instead of numbers! That's because they contain symbols like `₹`, `%`, and `,` — very common in real, uncleaned CSV data. We can't compute a mean or filter numerically on a text column, so let's clean these up next.

### ▶ **A Quick Data Cleaning Step**

We'll strip out the extra symbols and convert these columns to proper numeric types using `.str.replace()` and `pd.to_numeric()`. Setting `errors="coerce"` turns any value that still can't be converted (like a stray `|` in the ratings column) into `NaN` instead of crashing.

In [ ]:
#This line cleans up the discounted_price column, which stores values like "₹1,099" as plain text. The first .str.replace("₹", "", regex=False) strips out the rupee symbol, turning "₹399" into "399".
#That result is immediately chained into a second .str.replace(",", "", regex=False), which removes commas, turning "1,099" into "1099"
#Once the string is a clean number, .astype(float) converts it from text into an actual numeric type so it can be used in math, comparisons, and aggregation.
#The regex=False argument just tells pandas to treat "₹" and "," as literal characters rather than regex patterns.
df["discounted_price"] = df["discounted_price"].str.replace("₹", "", regex=False).str.replace(",", "", regex=False).astype(float)
df["actual_price"] = df["actual_price"].str.replace("₹", "", regex=False).str.replace(",", "", regex=False).astype(float)
df["discount_percentage"] = df["discount_percentage"].str.replace("%", "", regex=False).astype(float)
df["rating_count"] = df["rating_count"].str.replace(",", "", regex=False)
#This converts the now comma-free rating_count strings into numbers using pd.to_numeric() instead of .astype(float).
#The reason for the switch is that rating_count has a couple of missing or blank entries, which would cause .astype(float) to crash.
#pd.to_numeric() with errors="coerce" is more forgiving — anything it can't convert becomes NaN instead of raising an error, so the rest of the column still converts successfully.
df["rating_count"] = pd.to_numeric(df["rating_count"], errors="coerce")
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

product_id              object
product_name            object
category                object
discounted_price       float64
actual_price           float64
discount_percentage    float64
rating                 float64
rating_count           float64
about_product           object
user_id                 object
user_name               object
review_id               object
review_title            object
review_content          object
img_link                object
product_link            object
dtype: object

Much better — these are now `float64` columns we can actually do math on. The `category` column is also a bit messy: it stores a full hierarchy like `Electronics|Mobiles|SmartWatches` separated by `|`. Let's pull out just the top-level category for easier grouping later.

In [ ]:
# This line creates a new column called "main_category" from the existing "category" column.
# The .str.split("|") splits each category wherever the "|" symbol appears.
# For example, "Electronics|Mobiles|Smartphones" becomes ["Electronics", "Mobiles", "Smartphones"].
# The .str[0] selects the first element, "Electronics", which represents the main category.
# This value is then stored in the new "main_category" column.

df["main_category"] = df["category"].str.split("|").str[0]

# This line counts how many times each unique main category appears in the "main_category" column.
# It helps us understand how many products belong to each main category.
# The results are then printed on the screen.

print(df["main_category"].value_counts())

main_category
Electronics              526
Computers&Accessories    453
Home&Kitchen             448
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64

### ▶ **Pandas Series**
A **Series** is a one-dimensional labeled array — think of it as a single column of a DataFrame, or a supercharged list where each value has an associated index label.

In [ ]:
marks = pd.Series([85, 90, 78, 92], index=["Math", "Physics", "Chemistry", "Biology"])
print(marks)

Math         85
Physics      90
Chemistry    78
Biology      92
dtype: int64

You can access elements by their **label** or by their **position**.

In [ ]:
print(marks["Physics"])   # by label
print(marks.iloc[1])       # by position

90
90

A single column of a DataFrame is itself a Series.

In [ ]:
ratings = df["rating"]
print(ratings)
print(type(ratings))

0       4.2
1       4.0
2       3.9
3       4.2
4       4.2
       ...
1460    4.0
1461    4.1
1462    3.6
1463    4.0
1464    4.3
Name: rating, Length: 1465, dtype: float64
<class 'pandas.core.series.Series'>

### ▶ **Pandas DataFrames**

A **DataFrame** is a 2D labeled table, like a spreadsheet or SQL table. It's made up of multiple Series (columns) that share the same index.

You can build a DataFrame directly from a dictionary, where keys become column names.

In [ ]:
data = {
        "Product": ["Pen", "Notebook", "Eraser", "Sharpener"],
        "Price": [10, 40, 5, 8],
        "Stock": [100, 60, 200, 150]}
products_df = pd.DataFrame(data)
products_df

     Product  Price  Stock
0        Pen     10    100
1   Notebook     40     60
2     Eraser      5    200
3  Sharpener      8    150

### ▶ **Basic Indexing**

Pandas gives you a few different ways to select data from the Amazon DataFrame (`df`):
* `df["col"]` or `df[["col1", "col2"]]` – select column(s)
* `df.loc[]` – select rows/columns by **label**
* `df.iloc[]` – select rows/columns by **integer position**

In [ ]:
# Selecting a single column
print(df["product_name"])

0       Wayona Nylon Braided USB to Lightning Fast Cha...
1       Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2       Sounce Fast Phone Charging Cable & Data Sync U...
3       boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4       Portronics Konnect L 1.2M Fast Charging 3A 8 P...
                              ...
1460    Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1461    Prestige Delight PRWO Electric Rice Cooker (1 ...
1462    Bajaj Majesty RX10 2000 Watts Heat Convector R...
1463    Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1464    Borosil Jumbo 1000-Watt Grill Sandwich Maker (...
Name: product_name, Length: 1465, dtype: object

In [ ]:
# Selecting multiple columns
print(df[["product_name", "discounted_price", "rating"]])

                                           product_name  discounted_price  \
0     Wayona Nylon Braided USB to Lightning Fast Cha...             399.0
1     Ambrane Unbreakable 60W / 3A Fast Charging 1.5...             199.0
2     Sounce Fast Phone Charging Cable & Data Sync U...             199.0
3     boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...             329.0
4     Portronics Konnect L 1.2M Fast Charging 3A 8 P...             154.0
...                                                 ...               ...
1460  Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...             379.0
1461  Prestige Delight PRWO Electric Rice Cooker (1 ...            2280.0
1462  Bajaj Majesty RX10 2000 Watts Heat Convector R...            2219.0
1463  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...            1399.0
1464  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...            2863.0

      rating
0        4.2
1        4.0
2        3.9
3        4.2
4        4.2
...      ...
1460     4.0
1461     4.1
1462     3.6
1463     4.0
1464     4.3

[1465 rows x 3 columns]

In [ ]:
# loc - label based
print(df.loc[0])                                        # first row (by label/index)
print(df.loc[0, "product_name"])                        # value at row 0, column 'product_name'
print(df.loc[0:2, ["product_name", "rating"]])          # slice of rows, specific columns

product_id                                                    B07JW9H4J1
product_name           Wayona Nylon Braided USB to Lightning Fast Cha...
category               Computers&Accessories|Accessories&Peripherals|...
discounted_price                                                   399.0
actual_price                                                      1099.0
discount_percentage                                                 64.0
rating                                                               4.2
rating_count                                                     24269.0
about_product          High Compatibility : Compatible With iPhone 12...
user_id                AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
user_name              Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
review_id              R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
review_title           Satisfied,Charging is really fast,Value for mo...
review_content         Looks durable Charging is fine tooNo complains...
img_link               https://m.media-amazon.com/images/W/WEBP_40237...
product_link           https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
main_category                                      Computers&Accessories
Name: 0, dtype: object
Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)
                                        product_name  rating
0  Wayona Nylon Braided USB to Lightning Fast Cha...     4.2
1  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...     4.0
2  Sounce Fast Phone Charging Cable & Data Sync U...     3.9

In [ ]:
# iloc - position based
print(df.iloc[0])          # first row
print(df.iloc[0, 1])       # row 0, column at position 1 (product_name)
print(df.iloc[0:3, 0:3])   # first 3 rows, first 3 columns

product_id                                                    B07JW9H4J1
product_name           Wayona Nylon Braided USB to Lightning Fast Cha...
category               Computers&Accessories|Accessories&Peripherals|...
discounted_price                                                   399.0
actual_price                                                      1099.0
discount_percentage                                                 64.0
rating                                                               4.2
rating_count                                                     24269.0
about_product          High Compatibility : Compatible With iPhone 12...
user_id                AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
user_name              Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
review_id              R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
review_title           Satisfied,Charging is really fast,Value for mo...
review_content         Looks durable Charging is fine tooNo complains...
img_link               https://m.media-amazon.com/images/W/WEBP_40237...
product_link           https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
main_category                                      Computers&Accessories
Name: 0, dtype: object
Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)
   product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...

                                            category
0  Computers&Accessories|Accessories&Peripherals|...
1  Computers&Accessories|Accessories&Peripherals|...
2  Computers&Accessories|Accessories&Peripherals|...



```
# This is formatted as code
```

### ▶ **Filtering**

You can filter rows using **boolean conditions**, similar to how you'd filter a list with a condition, but pandas does it in a vectorized way across the whole column.

In [ ]:
# Products rated above 4.5
print(df[df["rating"] > 4.5])

      product_id                                       product_name  \
137   B08TGG316Z  10k 8k 4k HDMI Cable, Certified 48Gbps 1ms Ult...
174   B0BP7XLX48  Syncwire LTG to USB Cable for Fast Charging Co...
249   B09WN3SRC7  Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...
324   B0BQRJ3C47  REDTECH USB-C to Lightning Cable 3.3FT, [Apple...
447   B095RTJH1M  Spigen EZ Fit Tempered Glass Screen Protector ...
459   B0B23LW7NV  Spigen EZ Fit Tempered Glass Screen Protector ...
468   B0B244R4KB  Spigen EZ Fit Tempered Glass Screen Protector ...
571   B0B9BXKBC7  WeCool S5 Long Selfie Stick, with Large Reinfo...
775   B09ZHCJDP1  Amazon Basics Wireless Mouse | 2.4 GHz Connect...
820   B01J1CFO5I  Redgear MP35 Speed-Type Gaming Mousepad (Black...
853   B07X2L5Z8C  Logitech Pebble M350 Wireless Mouse with Bluet...
886   B01MQ2A86A  Logitech M331 Silent Plus Wireless Mouse, 2.4G...
964   B00NFD0ETQ  Logitech G402 Hyperion Fury USB Wired Gaming M...
976   B09XXZXQC1  Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz R...
1007  B0B9BXKBC7  WeCool S5 Long Selfie Stick, with Large Reinfo...
1119  B09JN37WBX  Lint Remover Woolen Clothes Lint Extractor Bat...
1127  B00SH18114  Ikea 903.391.72 Polypropylene Plastic Solid Be...
1145  B0BR4F878Q  Swiffer Instant Electric Water Heater Faucet T...
1201  B0BQ3K23Y1  Oratech Coffee Frother electric, milk frother ...
1216  B0BN6M3TCM  VRPRIME Lint Roller Lint Remover for Clothes, ...
1223  B0BM4KTNL1  FIGMENT Handheld Milk Frother Rechargeable, 3-...
1226  B0BLC2BYPX  Zuvexa USB Rechargeable Electric Foam Maker - ...
1275  B0BM9H2NY9  Multifunctional 2 in 1 Electric Egg Boiling St...
1289  B0BJ966M5K  Aquadpure Copper + Mineral RO+UV+UF 10 to 12 L...
1293  B09P1MFKG1  Melbon VM-905 2000-Watt Room Heater (ISI Certi...
1299  B0B53DS4TF  Instant Pot Air Fryer, Vortex 2QT, Touch Contr...
1381  B00K57MR22  Sujata Dynamix DX Mixer Grinder, 900W, 3 Jars ...
1388  B0BP89YBC1  Campfire Spring Chef Prolix Instant Portable W...
1428  B078JT7LTD  Sujata Dynamix, Mixer Grinder, 900 Watts, 3 Ja...

                                               category  discounted_price  \
137   Electronics|HomeTheater,TV&Video|Accessories|C...             999.0
174   Computers&Accessories|Accessories&Peripherals|...             399.0
249   Electronics|HomeTheater,TV&Video|Televisions|S...           77990.0
324   Computers&Accessories|Accessories&Peripherals|...             249.0
447   Electronics|Mobiles&Accessories|MobileAccessor...             999.0
459   Electronics|Mobiles&Accessories|MobileAccessor...             999.0
468   Electronics|Mobiles&Accessories|MobileAccessor...             999.0
571   Electronics|Mobiles&Accessories|MobileAccessor...            1799.0
775   Computers&Accessories|Accessories&Peripherals|...             499.0
820   Computers&Accessories|Accessories&Peripherals|...             299.0
853   Computers&Accessories|Accessories&Peripherals|...            1490.0
886   Computers&Accessories|Accessories&Peripherals|...            1295.0
964   Computers&Accessories|Accessories&Peripherals|...            1995.0
976                       Computers&Accessories|Tablets           26999.0
1007  Electronics|Mobiles&Accessories|MobileAccessor...            1799.0
1119  Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...             319.0
1127  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...             160.0
1145  Home&Kitchen|Heating,Cooling&AirQuality|WaterH...            1439.0
1201  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...             279.0
1216  Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...             499.0
1223  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...             699.0
1226  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...             499.0
1275  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...             699.0
1289  Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...            4999.0
1293  Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...             998.0
1299  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...            4995.0
1381  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...            6120.0
1388  Home&Kitchen|Heating,Cooling&AirQuality|WaterH...            1499.0
1428  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...            6120.0

      actual_price  discount_percentage  rating  rating_count  \
137         2399.0                 58.0     4.6        3664.0
174         1999.0                 80.0     5.0           5.0
249       139900.0                 44.0     4.7        5935.0
324          999.0                 75.0     5.0           NaN
447         2899.0                 66.0     4.6       26603.0
459         2899.0                 66.0     4.7        7779.0
468         2899.0                 66.0     4.6        6129.0
571         3999.0                 55.0     4.6         245.0
775         1000.0                 50.0     5.0          23.0
820          550.0                 46.0     4.6       33434.0
853         2295.0                 35.0     4.6       10652.0
886         1645.0                 21.0     4.6       12375.0
964         2895.0                 31.0     4.6       10760.0
976        37999.0                 29.0     4.6        2886.0
1007        3999.0                 55.0     4.6         245.0
1119         749.0                 57.0     4.6         124.0
1127         299.0                 46.0     4.6        2781.0
1145        1999.0                 28.0     4.8       53803.0
1201         499.0                 44.0     4.8          28.0
1216         999.0                 50.0     4.6          79.0
1223        1599.0                 56.0     4.7        1729.0
1226        1299.0                 62.0     4.7          54.0
1275        1599.0                 56.0     4.7        2300.0
1289       24999.0                 80.0     4.6         124.0
1293        2999.0                 67.0     4.6           9.0
1299       20049.0                 75.0     4.8        3964.0
1381        8478.0                 28.0     4.6        6550.0
1388        3500.0                 57.0     4.7        2591.0
1428        8073.0                 24.0     4.6        2751.0

                                          about_product  \
137   Certified HDMI Cable: The package has an offic...
174   This sturdy and durable cable made of tpe and ...
249   Resolution: 4K Ultra HD (3840 x 2160) | Refres...
324   💎[The Fastest Charge] - This iPhone USB C cabl...
447   Compatibility ; Glass Screen Protector Compati...
459   Compatibility ; Glass Screen Protector Compati...
468   Compatibility ; Glass Screen Protector Compati...
571   64" Tall Cell Phone Tripods with 7 section adj...
775   Reliable wireless connection up to 10m|Advance...
820   Speed-type surface mousepad is designed with t...
853   Modern, slim and beautiful Pebble shape Logite...
886   Quieter Click: Logitech’s SilentTouch Technolo...
964   HIGH SPEED TRACKING : Fusion engine delivers o...
976   Qualcomm Snapdragon 860 Octa-core processor | ...
1007  64" Tall Cell Phone Tripods with 7 section adj...
1119  Smoothly takes off the lint from fabric suitab...
1127  30 units|Perfect to Seal Food/Snack|Keep Food ...
1145  ✔Quick Electric Hot Water Tap Heating tube: hi...
1201  -Make delicious milk foam creamer for your dri...
1216  【CLEAN CLOTHES EVERY TIME】 : Our lint roller h...
1223  【Rechargeable Multi-Function Milk Frother】The ...
1226  The food taste stainless steel whisking head i...
1275                                     Egg Frying Pan
1289  RO technology reduces TDS, hardness, and remov...
1293  Lightweight (1.2 kg) for easy portability betw...
1299  VOLTAGE (230 Volts): Instant Vortex Air Fryer ...
1381  Warranty: 2 year warranty provided by the manu...
1388  Prolix Auto cut off feature: It is available w...
1428  Warranty: 2 year warranty provided by the manu...

                                                user_id  \
137   AFO7T5DJCA34LXNLPEMNTUPHBA3Q,AEOKQXQO42VI27RS7...
174   AF7EOXYL5K36BDP6PXF6K2TL5TPA,AEN7NV2P5WNHM7EXC...
249   AF6Z2OYIXRPZJHVYN2MFKKYHPHFQ,AH5SAORYVUN5MGIBL...
324                        AGJC5O5H5BBXWUV7WRIEIOOR3TVQ
447   AFDITJCB5D4EOPYZKGP5RGRJFVLA,AHFCEAPRZ44PZ2EVR...
459   AGQIXFPHABUZ2WPETGRYDB7VSMXA,AECPF7WFMUQ3TR7YT...
468   AHCJOEQEARI6IQ2XGJ6HTGQSRUXQ,AGBUKPO3CSYIJA4C4...
571   AFPYH3UF3GB4RNX3MX46AXFM2FTQ,AGWEQHJSUA4YCG44R...
775   AFLLEPVLIAH2DFSHAZ77KWFM72ZA,AHY2YZWK63CNZ626M...
820   AG6LARJ3IHDAIRVVN6WW4Q6JTPJA,AGRR4GPFNWDS7BAR4...
853   AGD6ND3S3MD2GWZDEJJ225BLLLUA,AF6WTL2BAI27FGX2B...
886   AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...
964   AFLGIDPC5GTJ4ET22CVZHSHBYCJA,AGFIU57KQ27B2HIIH...
976   AGIQYUS55MG4UWXTEF4PRMPZWPQA,AH4VWAKSTYSTM4XW5...
1007  AFPYH3UF3GB4RNX3MX46AXFM2FTQ,AGWEQHJSUA4YCG44R...
1119  AF4OLYBDMHJV5DUGONVIH7GU2V7Q,AEZNF3N52DQTHYBJ6...
1127  AE7M7M6QTDYEHQKAKXIWO2OVMBXQ,AESSDAJQCU3XKBAGY...
1145  AEU7DVFEL43XZ6T4D572W2ZLBRKQ,AGWOH7CFDMUVW52NM...
1201  AGRJZJKWKIE573KM5FWPOH4F7YCA,AEHV4VOLDQX5XYA42...
1216  AG56BWR4QA24HMU37HCG7LXA5BIQ,AHPMTDLBF66SKRERY...
1223  AGMHHTX7GPWHZAUTEYQOFEEDFMDQ,AEJJGJQCIEPL3ZBNU...
1226  AG6AS2KLLZMPPPEKF5RIJXTMA4FA,AEW6BC4YLRYKI5OZG...
1275  AFZ2YKWX4KR7MWSA6UOMEGGHT32A,AEP6WZ7AR6XDQSBFS...
1289  AHZJHJWFZLYD64GVP4PXVI2F4LXA,AEUCRZPOISXKHXMCZ...
1293  AENGRDSABHKCYNYJPZ2SML6FWVHA,AFNGD6S7UIHBQ2FNX...
1299  AGXJAYXZKJ6NCPSLX57MXJLQ3F6Q,AEQYSJWBP6DN2IV2L...
1381  AHNCY56JLPCF2AHRH3SO2RIKHYFA,AEBZKKPXROE4RBTBF...
1388  AEVX4JV3C4QR3Y3V3RJXQ2WZAR4Q,AHR5JZBK66QYZSEJ3...
1428  AGS4ODHNPY3TQGAIJFDY4I33URHA,AFFSSRKP2H3OGXCIJ...

                                              user_name  \
137                 Mandar Joglekar,Vasanth,Well person
174   Amazon Customer,kamal sahota,Pankaj,luvsmplcty...
249   David P.,Dr. ATUL THAKUR,Shriniwas Patil,Tahir...
324                                         Abdul Gafur
447   Abdul Moiz,Rupesh Patil,Devashis,Amruth Ramesh...
459   VK,Siddhi Prabhudesai,Prashant Nair,Srihare,Ni...
468   Prabhat Chaudhary,Anil Kumar.M,Prateek,Nilkant...
571   Sujili v,Paras Jain,Shailendra,supreeth achar,...
775   Rambeer kumar,Ramesh,Digambar Shelke,awadhesh ...
820   Jayaprakash,Keshav Rana,Mohit prime,Aman singh...
853   Ravi,Shrey,Deepthi,sreeraj,Priyadarshini P,Abd...
886   Awesome Shopper,Suresh madaka,Amazon Customer,...
964   Madhav Ashokan,parin patel,Arun S.,Salil Iyer,...
976   & I Am IronMan,Amazon Customer,Sayandeep Sarka...
1007  Sujili v,Paras Jain,Shailendra,supreeth achar,...
1119  Kewal k.,SANCHIT BHATIA,Akshit kumar,Hugu gupt...
1127  Dr.  Balasubramanian Pechimuthu,Abdul rehman,s...
1145                    Yogita g.,Amazon Customer,Mimsy
1201  Amazon Customer,Neha Mehta,Nischal Agarwal,tha...
1216  Kindle Customer,Naval Kishor Rustagi,Sudha,saj...
1223  123MovieTime,Ravneet S.,Akash,Mohd Amaan,Panka...
1226  shammi,Rippy Mittal,Kabeer,Kush,Vani Prabha,ne...
1275  Nitin G.,Veerasomachary,Roshan,Kunwar Indransh...
1289  Manish Mehekare,Rajesh,Nitesh singh,Lalit,Prat...
1293  Chanchal Gurjar,Shyam,Lalit Garg,Anil Kumar,PR...
1299  nikhil,Rituja Ray,Prasan Krishnan Karthikeyan,...
1381  Amazon Customer,Sai,Azim,john prabhakar,RAJA S...
1388  Srujan kumar,Sadhu s.,parveen sharma,Patel kau...
1428  Tengop,Jeevan Gaikwad,gunashekar,Vibha K.,Amaz...

                                              review_id  \
137          R1482M3Z6TF62M,RX9ISCNT5KUMA,RY1MX82BJD2VD
174   R1L2JNO4Y3BHYF,R2346F22YLZ9IG,R3A4GAQTCPE5U7,R...
249   R16HCZ0W1TRSMM,R12J7UKQ0FX3O9,R8729SR7LQFUU,R1...
324                                       RQXD5SAMMPC6L
447   RE1RVB3YIBPKD,R41RLIIPI7UUH,R232FT7DXDWX1C,R1V...
459   R13CIOIUD1D8UM,R17AIJTSM1FUNS,R3AJ1T3JVA8O9V,R...
468   R3C2WT83DOSL8U,R1GKC3NL9J667A,R2EQZSSQHG60ET,R...
571   R2MI4KSWYUEMDR,R2MNYKDL2UII1M,R2C6TUBM6IVLB0,R...
775   R76XPXMKXLWKH,R23S77AWPH5FP5,RK7Q6W5FOPESC,R2X...
820   R3358EO9V9WHQ0,R18X1NBWPX45CL,R34LKJ4RXUSRS3,R...
853   R17OGPT2IDXIGX,RBEABUL23L3HP,R15G3N5DHVIH7Y,RE...
886   R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...
964   R2W6BKEVXNT3N,R1W63TB4MX8482,R28EZ6Q89SHMHD,R1...
976   R2BT60BZIDC986,R17KDJGM0QOT3P,R2U9CP6B4FEVBN,R...
1007  R2MI4KSWYUEMDR,R2MNYKDL2UII1M,R2C6TUBM6IVLB0,R...
1119  R1XULCDQK9G8I7,RHPQ553ZWQIME,RNQB4SFH4DX7B,RMG...
1127  R1NAAWWJ35RMQR,R3S2CEY1ZBAKJJ,R38NYOW9S7HMO0,R...
1145       R2WHW4PEF14WOD,R2DCCZWUGI0O0K,R1FA1HH6VL1RAL
1201  R3907SDNN9VR5Y,R1NNMXA39722T8,RXQNT49DKJ26S,R2...
1216  R2QT3QBL25HBTG,R3E449S1ZWR7F9,RLHERK8U1LREO,R1...
1223  R1YXOQ6ZZI33LZ,R17FVMZGPYPOYZ,R23NCERA0R891T,R...
1226  R1M11VMLH6I3TN,R2OLOOGNHQ37ZA,R3PIVKT8BNMA4G,R...
1275  R2DHTJGY77MOP0,R36IXNHZC037AW,R3GPHUMRV75VWK,R...
1289  R410I44U1ORFS,R2EL6RDO42L8HA,R2LMSC4S998NYI,R2...
1293  R2REMFEEN6UKBC,R29TQDV31QHMAP,RSC1YPIBXFW9B,R3...
1299  R2FHIBV8JE4CTB,R315K0BCU0KVKO,RD129PA7KQQOR,R3...
1381  R2IMGTYKPMXP4N,R2LP7PV1I0Z1V0,R33UGZXCUN1PDT,R...
1388  RBPM3YRVWMMMK,RVY7BZCJPHJZU,R3KXHKIGWPT7IS,R1K...
1428  R1LBKT3YDVVW86,R2PNLSWFYW5QEF,R2I6NKZE7JWNY6,R...

                                           review_title  \
137   Fantastic Ultra High Speed HDMI cable,Amazing ...
174   Good,Superb quality,Good products  nice one,Wo...
249   Product installation was excellent  but delive...
324                                     Awesome Product
447   Easy to install but a bit slippery,Very good p...
459   Easy to install,Best screen guard and the easi...
468   Best For It’s Money!🔥,Nice quality, but comes ...
571   Good,Good Product but Little expensive.,Happy ...
775   Very responsive and stylish mouse,Simply Aweso...
820   Good product,Good quality,Good,Great mouse pad...
853   Sleek and battery efficient!,It's made for erg...
886   Good but the scroll is now damaged,Nice,Noisel...
964   very nice design and long lasting,Good mouse,L...
976   the only ANDROID tablet that makes sense in th...
1007  Good,Good Product but Little expensive.,Happy ...
1119  good,Overall good product but got stop inbetwe...
1127  It is Okay.,Amazing product and fast shipping,...
1145  Best Product,It’s expansive but it works well ...
1201  Oratech Best Coffee Frother,Great,My review ab...
1216  Superb,Very helpful and great quality,Exactly ...
1223  Nice product,Not as effective as claimed, just...
1226  Little kitchen helper,An amazing product,Very ...
1275  Amazing! Value for money!,Very easy to use,2 i...
1289  service is excellent,  installation guy is ver...
1293  It's good,Happy to purchase,Product is really ...
1299  Loved it,Good product,Good product,It's easy t...
1381  Best mixer,Best value for money,सबसे जरूरी बात...
1388  Felt very useful 👌 but cable is short,Good in ...
1428  Good product,Quality is great but chuteney jar...

                                         review_content  \
137   Absolutely value for money. I connect it with ...
174   Product is good in quality. Working good with ...
249   The delivery people were not careful with the ...
324   Quick delivery.Awesome ProductPacking was good...
447   I used my 13 pro without a screen guard for a ...
459   It is easy to install at home. The kit has all...
468   It’s A Good Purchase For Long term Personally ...
571   Good,Thoda sa kam stable hai, phone lagane ke ...
775   I really like this wireless mouse it has becam...
820   Quality of product is above average.,Good qual...
853   It's a good bluetooth mouse. Connects within 1...
886   - excellent piece of wireless mouse- reasonabl...
964   its really good product for gamers i would rec...
976   first i would like to comment on the tab marke...
1007  Good,Thoda sa kam stable hai, phone lagane ke ...
1119  https://m.media-amazon.com/images/W/WEBP_40237...
1127  It is Okay so far.,This product was amazing an...
1145  Must buy best Fabulous product I recommend thi...
1201  Overall, I love this Oratech Coffee frother an...
1216  Value for money,The quality of the tapes are a...
1223  Value for money,Not as effective as claimed, j...
1226  The first time I tried it send the eggs and th...
1275  Worth buying for eggetarians,Working great so ...
1289  I like the service most and the product,Note: ...
1293  It's good  nd amazing product,Very nice produc...
1299  I have used multiple air fryers. But this one ...
1381  Best mixer as compared to flimsy  350w,750w. W...
1388  I like instant heating, I didn't get warranty ...
1428  Got it with intact packaging open it up the mo...

                                               img_link  \
137   https://m.media-amazon.com/images/W/WEBP_40237...
174   https://m.media-amazon.com/images/I/317OoQfs1g...
249   https://m.media-amazon.com/images/I/51uVckL1jR...
324   https://m.media-amazon.com/images/I/31-q0xhaTA...
447   https://m.media-amazon.com/images/I/41Usew0lrW...
459   https://m.media-amazon.com/images/I/51EiPNlJDg...
468   https://m.media-amazon.com/images/I/51R2kfyMW5...
571   https://m.media-amazon.com/images/I/41fDM4QUfv...
775   https://m.media-amazon.com/images/I/31+Rg6Z46d...
820   https://m.media-amazon.com/images/W/WEBP_40237...
853   https://m.media-amazon.com/images/I/31DstM4dQ8...
886   https://m.media-amazon.com/images/W/WEBP_40237...
964   https://m.media-amazon.com/images/W/WEBP_40237...
976   https://m.media-amazon.com/images/I/31jUKdJdjH...
1007  https://m.media-amazon.com/images/I/41fDM4QUfv...
1119  https://m.media-amazon.com/images/W/WEBP_40237...
1127  https://m.media-amazon.com/images/I/41k+HQz9Jb...
1145  https://m.media-amazon.com/images/I/41+t2HWvwF...
1201  https://m.media-amazon.com/images/W/WEBP_40237...
1216  https://m.media-amazon.com/images/W/WEBP_40237...
1223  https://m.media-amazon.com/images/I/51oN+8Zs5Y...
1226  https://m.media-amazon.com/images/I/41714O1hnm...
1275  https://m.media-amazon.com/images/W/WEBP_40237...
1289  https://m.media-amazon.com/images/W/WEBP_40237...
1293  https://m.media-amazon.com/images/I/41xLjSyJtY...
1299  https://m.media-amazon.com/images/W/WEBP_40237...
1381  https://m.media-amazon.com/images/I/41cZE9HcRU...
1388  https://m.media-amazon.com/images/W/WEBP_40237...
1428  https://m.media-amazon.com/images/I/415634DtKf...

                                           product_link          main_category
137   https://www.amazon.in/Cable-Certified-48Gbps-U...            Electronics
174   https://www.amazon.in/Syncwire-Cable-Charging-...  Computers&Accessories
249   https://www.amazon.in/Sony-Bravia-inches-Googl...            Electronics
324   https://www.amazon.in/REDTECH-Lightning-Certif...  Computers&Accessories
447   https://www.amazon.in/Spigen-Tempered-Screen-P...            Electronics
459   https://www.amazon.in/Spigen-Tempered-Screen-P...            Electronics
468   https://www.amazon.in/Spigen-Tempered-Screen-P...            Electronics
571   https://www.amazon.in/WeCool-Reinforced-Functi...            Electronics
775   https://www.amazon.in/Wireless-Connection-Batt...  Computers&Accessories
820   https://www.amazon.in/Redgear-MP35-Speed-Type-...  Computers&Accessories
853   https://www.amazon.in/Logitech-Pebble-M350-Wir...  Computers&Accessories
886   https://www.amazon.in/Logitech-Silent-Wireless...  Computers&Accessories
964   https://www.amazon.in/Logitech-Hyperion-Ultra-...  Computers&Accessories
976   https://www.amazon.in/Snapdragon-Resolution-Re...  Computers&Accessories
1007  https://www.amazon.in/WeCool-Reinforced-Functi...            Electronics
1119  https://www.amazon.in/Remover-Clothes-Extracto...           Home&Kitchen
1127  https://www.amazon.in/Ikea-903-391-72-Sealing-...           Home&Kitchen
1145  https://www.amazon.in/Swiffer-Instant-Electric...           Home&Kitchen
1201  https://www.amazon.in/Oratech-electric-cappucc...           Home&Kitchen
1216  https://www.amazon.in/VRPRIME-Remover-Reusable...           Home&Kitchen
1223  https://www.amazon.in/FIGMENT-Rechargeable-Dec...           Home&Kitchen
1226  https://www.amazon.in/Zuvexa-Rechargeable-Elec...           Home&Kitchen
1275  https://www.amazon.in/Multifunctional-Electric...           Home&Kitchen
1289  https://www.amazon.in/Aquadpure-Copper-ADJUSTE...           Home&Kitchen
1293  https://www.amazon.in/Melbon-Blower-Heater-200...           Home&Kitchen

In [ ]:
# Products in the Electronics main category
print(df[df["main_category"] == "Electronics"])

      product_id                                       product_name  \
12    B07KSMBL2H  AmazonBasics Flexible Premium HDMI Cable (Blac...
16    B0B6F7LX4C  MI 80 cm (32 inches) 5A Series HD Ready Smart ...
19    B08DPLCM6T  LG 80 cm (32 inches) HD Ready Smart LED TV 32L...
21    B085194JFL  tizum HDMI to VGA Adapter Cable 1080P for Proj...
22    B09F6S8BT6  Samsung 80 cm (32 Inches) Wondertainment Serie...
...          ...                                                ...
1012  B014SZPBM4           Duracell Ultra Alkaline D Battery, 2 Pcs
1015  B078W65FJ7  boAt BassHeads 900 On-Ear Wired Headphones wit...
1016  B08S74GTBT  Zebronics Astra 10 Portable Wireless BT v5.0 S...
1017  B0B9BD2YL4  KINGONE Wireless Charging Pencil (2nd Generati...
1021  B07W7Z6DVL  Infinity (JBL Fuze 100, Wireless Portable Blue...

                                               category  discounted_price  \
12    Electronics|HomeTheater,TV&Video|Accessories|C...             219.0
16    Electronics|HomeTheater,TV&Video|Televisions|S...           13999.0
19    Electronics|HomeTheater,TV&Video|Televisions|S...           13490.0
21    Electronics|HomeTheater,TV&Video|Accessories|C...             279.0
22    Electronics|HomeTheater,TV&Video|Televisions|S...           13490.0
...                                                 ...               ...
1012  Electronics|GeneralPurposeBatteries&BatteryCha...             380.0
1015  Electronics|Headphones,Earbuds&Accessories|Hea...             849.0
1016     Electronics|HomeAudio|Speakers|OutdoorSpeakers             799.0
1017  Electronics|Mobiles&Accessories|MobileAccessor...            2599.0
1021     Electronics|HomeAudio|Speakers|OutdoorSpeakers            1499.0

      actual_price  discount_percentage  rating  rating_count  \
12           700.0                 69.0     4.4      426973.0
16         24999.0                 44.0     4.2       32840.0
19         21990.0                 39.0     4.3       11976.0
21           499.0                 44.0     3.7       10962.0
22         22900.0                 41.0     4.3       16299.0
...            ...                  ...     ...           ...
1012         400.0                  5.0     4.4        2111.0
1015        2490.0                 66.0     4.2       91188.0
1016        1999.0                 60.0     3.7         418.0
1017        6999.0                 63.0     4.5        1526.0
1021        2999.0                 50.0     4.1       25262.0

                                          about_product  \
12    Flexible, lightweight HDMI cable for connectin...
16    Note : The brands, Mi and Xiaomi, are part of ...
19    Resolution: HD Ready (1366x768) | Refresh Rate...
21    Superior Stability: Built-in advanced Certifie...
22    Resolution: HD Ready (1366x768) | Refresh Rate...
...                                                 ...
1012  Long Lasting Power Guaranteed|Our best battery...
1015  Enjoy powerful, dynamic sound with punchy bass...
1016  Wireless Portable Speaker with Mobile Holder|E...
1017  【2022 latest iPad Magnetic Charging】 The lates...
1021  Compact Portable Bluetooth Speakers. Wireless ...

                                                user_id  \
12    AEYJ5I6JZZPOJB6MGWRQOHRQLPSQ,AFY5TVFOMVHGBPBTI...
16    AHEVOQADJSSRX7DS325HSFLMP7VQ,AG7XYZRCSKX6G2OLO...
19    AHBNKB74LGTYUOKPAJBSKNFV45CA,AFIECTV45ADX5YPTE...
21    AEO5FHWNOSFBT554DKQAG4ICBGFQ,AGIQ5Y7Q4MKZ542KK...
22    AHEVO4Q5NM4YXMG2HDDXC5XMBGRQ,AFZPH7ZAWX5VDY3HO...
...                                                 ...
1012  AEGQJH2NIAS54T7WKAHKVEO4B67A,AFDH4NWAAHAVKPQVB...
1015  AFM6IHWXNLXOBO3JZTO5DN5QJROQ,AHXEMXDI7LE4FLGEU...
1016  AE42EZDBUFSJZGL66F275G54PSUA,AHFGOPCKQ4SMDFRKG...
1017  AEAX7BRPDS3NSYCZQBQDL5DGZDVA,AFI76LT4UP2L3SFJM...
1021  AHBISYTXOMEMKDTXVEKH57D2X3RA,AEOSGU32LYFVLXEHE...

                                              user_name  \
12    Rishav Gossain,Shashank Mallamraju,Purnendu,gu...
16    Manoj maddheshiya,Manoj Kumar Sahoo,Saumil s.,...
19    NIRMAL.N,Manoj kumar,SOMNATH DAS,Harsha,Pradhu...
21    aditya d.,Paranthaman,ashik rahman c,Rajas c.,...
22    Rahman Ali,MARIYA DASS,Md Aftab,roshan s.,Moha...
...                                                 ...
1012  Md asif akhter,KIRAN T,Hanuman sarda,Pranav Ch...
1015  Sayan,Lucky,Anish Kadivar,Surjit pharmacist,An...
1016  ESWARAN,Amal Gopinath,DODDI GOVINDA RAO,Vinita...
1017  Ak,Jitesh,anil,Umpo,G'DAS ENTERPRISES,Neetu,Va...
1021  Sreekumar KURUMALIKKAL,Mukund,ADITYA GUPTA,dev...

                                              review_id  \
12    R1FKOKZ3HHKJBZ,R2WNMZI1EXTA0H,RCA1M3W4RIXUR,R3...
16    R13UTIA6KOF6QV,R2UGDZSGFF01K7,RHHIZ45VYU5X6,R1...
19    R2PNR69G0BQG2F,R31A0WWDEYMKEW,R2C4XEWFLVU7JV,R...
21    R1GYK05NN6747O,R1J21BZ29NGQF9,R16JCHEILBYOMW,R...
22    R1SN0D4DFBKAZI,R1SX5L77L2CD6V,R1NAZ6M4QBUJMK,R...
...                                                 ...
1012  R1RXFMVZ8EKN3Q,R2YX4PL3F59OHC,RUDJ9ISAQDD3B,R3...
1015  R1ENIO169KEJPW,R1V9WVGGU6G0SZ,R1CS1EB6REPXU6,R...
1016  R1PUDD2V2KQP06,R1LRN5EFJ0Y717,R1S7Q7UW9FO9LY,R...
1017  R1HOV97NOJFX4W,R3BIRU7WH404ND,RAU26U2KP1OQH,R1...
1021  R2NQLS6I62ASDV,RIT3TAH74G3JM,R3V03S1XKJWJ4F,RT...

                                           review_title  \
12    It's quite good and value for money,Works well...
16    It is the best tv if you are getting it in 10-...
19    Sound quality,Very nice,Value for money,Good,G...
21    Good product ; Average Finishing,Save it purpo...
22    Good,Sound is very low another brand comparing...
...                                                 ...
1012  Battery,Good buy,Bigger than expected,Best Bat...
1015  Definitely good but wire is too short,Never ex...
1016  Super product,Worst antenna.... It came out wh...
1017  Quite Good,good pencil,Value for money,Brillia...
1021  Good Handy Bluetooth Speaker,Very Nice,Medium,...

                                         review_content  \
12    I am using it for 14 days now. The experience ...
16    Pros- xiomi 5a is best in budget-Nice picture ...
19    LG was always Good , correct delivery, good se...
21    This connector has provided as a boon for my o...
22    Overall good.,TV picture ok smart betterSound ...
...                                                 ...
1012  Duracell never disappoint you,Good,https://m.m...
1015  Product is good. It's definitely a peace for e...
1016  Super product,Worst product,Too good product,G...
1017  After 10 days of use bhaut acha chl rha ha and...
1021  Good Bass and Treble. Good Sound Quality.,Good...

                                               img_link  \
12    https://m.media-amazon.com/images/I/41nPYaWA+M...
16    https://m.media-amazon.com/images/I/51fmHk3km+...
19    https://m.media-amazon.com/images/W/WEBP_40237...
21    https://m.media-amazon.com/images/W/WEBP_40237...
22    https://m.media-amazon.com/images/W/WEBP_40237...
...                                                 ...
1012  https://m.media-amazon.com/images/I/51BGUyveMf...
1015  https://m.media-amazon.com/images/W/WEBP_40237...
1016  https://m.media-amazon.com/images/I/41uoxHxPDa...
1017  https://m.media-amazon.com/images/I/217Lv1D3bH...
1021  https://m.media-amazon.com/images/W/WEBP_40237...

                                           product_link main_category
12    https://www.amazon.in/AmazonBasics-Flexible-HD...   Electronics
16    https://www.amazon.in/MI-inches-Ready-Android-...   Electronics
19    https://www.amazon.in/LG-inches-Ready-Smart-32...   Electronics
21    https://www.amazon.in/Adapter-Projector-Comput...   Electronics
22    https://www.amazon.in/Samsung-Inches-Wondertai...   Electronics
...                                                 ...           ...
1012  https://www.amazon.in/Duracell-Alkaline-Batter...   Electronics
1015  https://www.amazon.in/Heads-900-Wired-Headphon...   Electronics
1016  https://www.amazon.in/ZEBRONICS-Zeb-Astra-Wire...   Electronics
1017  https://www.amazon.in/Wireless-Generation-Sens...   Electronics
1021  https://www.amazon.in/Infinity-Fuze-100-Waterp...   Electronics

[526 rows x 17 columns]

You can also combine multiple conditions using `&` (and), `|` (or). Each condition must be wrapped in parentheses.

In [ ]:
# Electronics products with a discount of over 50%
print(df[(df["main_category"] == "Electronics") & (df["discount_percentage"] > 50)])

      product_id                                       product_name  \
12    B07KSMBL2H  AmazonBasics Flexible Premium HDMI Cable (Blac...
25    B01M4GGIVU  Tizum High Speed HDMI Cable with Ethernet | Su...
48    B09L8DSSFH  7SEVEN® Compatible for Samsung Smart 4K Ultra ...
55    B01N90RZ4M                          Tata Sky Universal Remote
60    B07B275VN9  Airtel DigitalTV DTH Television, Setup Box Rem...
...          ...                                                ...
999   B08SMJT55F  boAt Stone 250 Portable Wireless Speaker with ...
1007  B0B9BXKBC7  WeCool S5 Long Selfie Stick, with Large Reinfo...
1015  B078W65FJ7  boAt BassHeads 900 On-Ear Wired Headphones wit...
1016  B08S74GTBT  Zebronics Astra 10 Portable Wireless BT v5.0 S...
1017  B0B9BD2YL4  KINGONE Wireless Charging Pencil (2nd Generati...

                                               category  discounted_price  \
12    Electronics|HomeTheater,TV&Video|Accessories|C...             219.0
25    Electronics|HomeTheater,TV&Video|Accessories|C...             199.0
48    Electronics|HomeTheater,TV&Video|Accessories|R...             399.0
55    Electronics|HomeTheater,TV&Video|Accessories|R...             230.0
60    Electronics|HomeTheater,TV&Video|Accessories|R...             179.0
...                                                 ...               ...
999    Electronics|HomeAudio|Speakers|BluetoothSpeakers            1199.0
1007  Electronics|Mobiles&Accessories|MobileAccessor...            1799.0
1015  Electronics|Headphones,Earbuds&Accessories|Hea...             849.0
1016     Electronics|HomeAudio|Speakers|OutdoorSpeakers             799.0
1017  Electronics|Mobiles&Accessories|MobileAccessor...            2599.0

      actual_price  discount_percentage  rating  rating_count  \
12           700.0                 69.0     4.4      426973.0
25           699.0                 72.0     4.2       12153.0
48           999.0                 60.0     3.6         493.0
55           499.0                 54.0     3.7        2960.0
60           799.0                 78.0     3.7        2201.0
...            ...                  ...     ...           ...
999         3990.0                 70.0     4.2        2908.0
1007        3999.0                 55.0     4.6         245.0
1015        2490.0                 66.0     4.2       91188.0
1016        1999.0                 60.0     3.7         418.0
1017        6999.0                 63.0     4.5        1526.0

                                          about_product  \
12    Flexible, lightweight HDMI cable for connectin...
25    Latest Standard HDMI A Male to A Male Cable: S...
48    1. 7SEVEN Compatible remote suitable for all O...
55    Universal remote control|Ensures long lastinga...
60    This is Generic Airtel Tv Remote|Universal con...
...                                                 ...
999   Power- Get ready to be enthralled by the 5W RM...
1007  64" Tall Cell Phone Tripods with 7 section adj...
1015  Enjoy powerful, dynamic sound with punchy bass...
1016  Wireless Portable Speaker with Mobile Holder|E...
1017  【2022 latest iPad Magnetic Charging】 The lates...

                                                user_id  \
12    AEYJ5I6JZZPOJB6MGWRQOHRQLPSQ,AFY5TVFOMVHGBPBTI...
25    AGVUE2NFN2MQEOQ4PR525B2ZI5PQ,AFO4M4BQ2WS7A3LPK...
48    AH5G2FWQ6AJBXK2IDCA22BNQTT2A,AEEV73PQDYYMSQSW4...
55    AEOM4KLP4SKKVSOCAMP7ORLGPGUA,AE4VKQV43AJEZDWE4...
60    AED54H4JXQGZT6GANH6PJN4SNU7Q,AF652OHBGHAEER2HL...
...                                                 ...
999   AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...
1007  AFPYH3UF3GB4RNX3MX46AXFM2FTQ,AGWEQHJSUA4YCG44R...
1015  AFM6IHWXNLXOBO3JZTO5DN5QJROQ,AHXEMXDI7LE4FLGEU...
1016  AE42EZDBUFSJZGL66F275G54PSUA,AHFGOPCKQ4SMDFRKG...
1017  AEAX7BRPDS3NSYCZQBQDL5DGZDVA,AFI76LT4UP2L3SFJM...

                                              user_name  \
12    Rishav Gossain,Shashank Mallamraju,Purnendu,gu...
25    Yashpreet Singh,Abiram,Aakaash Ramchandani,Ami...
48    MONTY,Qais Makani,Rajat Shuvra Roy,Amith PJ,Dh...
55    Jacob.,Dinesh Ahuja,Ashith,Pravin Chavhan,Anil...
60    Periyasamy,Madhusudhanan,S Salman palka,Sumit,...
...                                                 ...
999   Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...
1007  Sujili v,Paras Jain,Shailendra,supreeth achar,...
1015  Sayan,Lucky,Anish Kadivar,Surjit pharmacist,An...
1016  ESWARAN,Amal Gopinath,DODDI GOVINDA RAO,Vinita...
1017  Ak,Jitesh,anil,Umpo,G'DAS ENTERPRISES,Neetu,Va...

                                              review_id  \
12    R1FKOKZ3HHKJBZ,R2WNMZI1EXTA0H,RCA1M3W4RIXUR,R3...
25    R2DIHMHOPYEASB,R24RHE9B30YXWQ,R3DYXQZQA6PPHM,R...
48    RVEWH0LAEO3NH,R3E42NTD6HXN1Q,R3IC0VLPIDBPTY,R1...
55    RJ19CW7WCSFUI,R3W3PK017U6SIG,RJB32KHP5D5O3,R3P...
60    R3MXMT6V18JJ1P,R1BQE9L2M5L12J,R369X3BEG4QPC4,R...
...                                                 ...
999   RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...
1007  R2MI4KSWYUEMDR,R2MNYKDL2UII1M,R2C6TUBM6IVLB0,R...
1015  R1ENIO169KEJPW,R1V9WVGGU6G0SZ,R1CS1EB6REPXU6,R...
1016  R1PUDD2V2KQP06,R1LRN5EFJ0Y717,R1S7Q7UW9FO9LY,R...
1017  R1HOV97NOJFX4W,R3BIRU7WH404ND,RAU26U2KP1OQH,R1...

                                           review_title  \
12    It's quite good and value for money,Works well...
25    Cheap product and same is the performance but ...
48    Overall Good,Works well. Will comment on durab...
55    The button contacts are not very good.,Okay fo...
60    Simple and good,Satisfied!,Good one,Light weig...
...                                                 ...
999   Strudy, Awesome connectivity........but bass i...
1007  Good,Good Product but Little expensive.,Happy ...
1015  Definitely good but wire is too short,Never ex...
1016  Super product,Worst antenna.... It came out wh...
1017  Quite Good,good pencil,Value for money,Brillia...

                                         review_content  \
12    I am using it for 14 days now. The experience ...
25    The signal is too unstable once connect you ne...
48    Overall replacement of original samsung remote...
55    The button contacts are not very good.,Doesn't...
60    Nice,Works very well with Airtel DTH. The pair...
...                                                 ...
999   The LED light is vibrant with multiple form se...
1007  Good,Thoda sa kam stable hai, phone lagane ke ...
1015  Product is good. It's definitely a peace for e...
1016  Super product,Worst product,Too good product,G...
1017  After 10 days of use bhaut acha chl rha ha and...

                                               img_link  \
12    https://m.media-amazon.com/images/I/41nPYaWA+M...
25    https://m.media-amazon.com/images/I/41da4tk7N+...
48    https://m.media-amazon.com/images/W/WEBP_40237...
55    https://m.media-amazon.com/images/I/315GdnF+Lc...
60    https://m.media-amazon.com/images/W/WEBP_40237...
...                                                 ...
999   https://m.media-amazon.com/images/I/51J45Dcgkt...
1007  https://m.media-amazon.com/images/I/41fDM4QUfv...
1015  https://m.media-amazon.com/images/W/WEBP_40237...
1016  https://m.media-amazon.com/images/I/41uoxHxPDa...
1017  https://m.media-amazon.com/images/I/217Lv1D3bH...

                                           product_link main_category
12    https://www.amazon.in/AmazonBasics-Flexible-HD...   Electronics
25    https://www.amazon.in/TIZUM-Slim-1-5m-HDMI-Cab...   Electronics
48    https://www.amazon.in/7SEVENTM-Compatible-Repl...   Electronics
55    https://www.amazon.in/TATASKY-Universal-Remote...   Electronics
60    https://www.amazon.in/Airtel-Digital-Remote-Co...   Electronics
...                                                 ...           ...
999   https://www.amazon.in/boAt-Stone-250-Playback-...   Electronics
1007  https://www.amazon.in/WeCool-Reinforced-Functi...   Electronics
1015  https://www.amazon.in/Heads-900-Wired-Headphon...   Electronics
1016  https://www.amazon.in/ZEBRONICS-Zeb-Astra-Wire...   Electronics
1017  https://www.amazon.in/Wireless-Generation-Sens...   Electronics

[276 rows x 17 columns]

### ▶ **Summary Operations**

Pandas provides quick built-in methods to summarize your data:
* `.describe()` – summary statistics for numeric columns
* `.mean()`, `.sum()`, `.min()`, `.max()`, `.median()`, `.std()` – column-wise stats
* `.value_counts()` – frequency count of unique values (useful on a single column)

In [ ]:
print(df.describe())

       discounted_price   actual_price  discount_percentage       rating  \
count       1465.000000    1465.000000          1465.000000  1464.000000
mean        3125.310874    5444.990635            47.691468     4.096585
std         6944.304394   10874.826864            21.635905     0.291674
min           39.000000      39.000000             0.000000     2.000000
25%          325.000000     800.000000            32.000000     4.000000
50%          799.000000    1650.000000            50.000000     4.100000
75%         1999.000000    4295.000000            63.000000     4.300000
max        77990.000000  139900.000000            94.000000     5.000000

        rating_count
count    1463.000000
mean    18295.541353
std     42753.864952
min         2.000000
25%      1186.000000
50%      5179.000000
75%     17336.500000
max    426973.000000

In [ ]:
print("Average Rating:", df["rating"].mean())
print("Highest Discounted Price:", df["discounted_price"].max())
print("Lowest Discounted Price:", df["discounted_price"].min())
print("Average Discount %:", df["discount_percentage"].mean())

Average Rating: 4.096584699453552
Highest Discounted Price: 77990.0
Lowest Discounted Price: 39.0
Average Discount %: 47.69146757679181

In [ ]:
print(df["main_category"].value_counts())

main_category
Electronics              526
Computers&Accessories    453
Home&Kitchen             448
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64




### ▶ **Practice Questions**

> **Note:** For this practice set, you'll be working with a **new dataset, `house_prices.csv`** (not `amazon.csv` from the earlier examples). Make sure you download `house_prices.csv` and load *that* file.

Q1. Loading the Dataset

Load house_prices.csv into a Pandas DataFrame named df. Display the first 5 rows and last 5 rows.

Q2. Inspecting the Dataset

Print the following:

Shape of the DataFrame
Column names
Data types of all columns


Q3. Understanding the Data

Use .info() to inspect the dataset. Identify three columns that are stored as object data type.

Q4. Data Cleaning — Price

The Amount(in rupees) column contains values such as:

42 Lac
98 Lac
1.40 Cr
25 Lac

Remove the extra spaces from this column and display the first 10 values.

Q5. Data Cleaning — Carpet Area

The Carpet Area column contains values such as:

500 sqft
473 sqft
779 sqft

Remove " sqft" from the values and convert the column into a numerical type.

Q6. Creating a Series

Create a Pandas Series using the following house prices:

[42, 98, 140, 25, 160]

Use the following labels:

House1, House2, House3, House4, House5

Display the price of House3 using its label and House5 using its position.

Q7. Selecting Columns

From the DataFrame, display only these columns:

Title
location
Price (in rupees)
Furnishing

Q8. Using .loc[]

Using .loc[], display rows 10 to 14 and only the following columns:

Title
location
Status
Furnishing

Q9. Using .iloc[]

Using .iloc[], display rows 5 to 9 and columns 1 to 5.

Q10. Filtering by Location

Display all houses where the location is "thane".

Q11. Filtering by Furnishing

Display all houses where Furnishing is "Furnished".

Q12. Multiple Conditions

Find houses that satisfy both conditions:

location is "thane"
Furnishing is "Unfurnished"

Display only:

Title
location
Furnishing
Price (in rupees)

Q13. Summary Operation

Using the Price (in rupees) column, find:

Average price
Maximum price
Minimum price

Q14. Summary Operation

Find the following for the Price (in rupees) column:

Median price
Average price

Also use .describe() to display the summary statistics.


Q15. Category Counting

Use value_counts() to find:

Number of properties for each Furnishing type.
Number of properties for each Transaction type.
Which Furnishing type occurs most frequently.